ALTER TABLE `Expense`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `ExpenseTransaction`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `Loan`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `LoanTransaction`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `LoanRepayment`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `Investment`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `Asset`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `BankAccount`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `BankCard`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `ZakatCalculationItem`
  MODIFY COLUMN `notes` LONGTEXT NULL;

ALTER TABLE `ZakatPayment`
  MODIFY COLUMN `notes` LONGTEXT NULL;
