CREATE TABLE `stock` (
    `id` VARCHAR(191) NOT NULL,
    `fundName` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NULL,
    `launchDate` DATETIME(3) NULL,
    `validityDate` DATETIME(3) NOT NULL,
    `repurchasePrice` DECIMAL(19, 6) NULL,
    `offerPrice` DECIMAL(19, 6) NULL,
    `navPrice` DECIMAL(19, 6) NULL,
    `managementFee` DECIMAL(19, 6) NULL,
    `trusteeFee` DECIMAL(19, 6) NULL,
    `regulatoryFee` DECIMAL(19, 6) NULL,
    `leviesAndTaxes` DECIMAL(19, 6) NULL,
    `transactionExpenses` DECIMAL(19, 6) NULL,
    `thirdPartyExpenses` DECIMAL(19, 6) NULL,
    `otherExpenses` DECIMAL(19, 6) NULL,
    `terWithLevies` DECIMAL(19, 6) NULL,
    `terWithoutLevies` DECIMAL(19, 6) NULL,
    `mtdReturn` DECIMAL(19, 6) NULL,
    `fytdReturn` DECIMAL(19, 6) NULL,
    `cytdReturn` DECIMAL(19, 6) NULL,
    `fy25Return` DECIMAL(19, 6) NULL,
    `fy24Return` DECIMAL(19, 6) NULL,
    `sinceInceptionReturn` DECIMAL(19, 6) NULL,
    `rawValues` JSON NOT NULL,
    `sourceUrl` VARCHAR(512) NOT NULL,
    `scrapedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `stock_fundName_validityDate_key`(`fundName`, `validityDate`),
    INDEX `stock_validityDate_idx`(`validityDate`),
    INDEX `stock_category_idx`(`category`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
